import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{getFirestore,doc,setDoc,getDoc,collection,query,where,getDocs,onSnapshot,serverTimestamp,runTransaction,waitForPendingWrites,enableNetwork}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
let user=null,member=null,householdId="",role="member",stateRef=null,unsubState=null,unsubMembers=null,saveTimer=null,remote=false,cloudReady=false,revision=0,pendingJson="",saving=false;
const status=(kind,text)=>window.updateSyncStatus?.(kind,text);
const diagnostic=()=>`Project: ${firebaseConfig.projectId}\nHousehold: ${householdId||"not loaded"}\nRole: ${role}\nCloud revision: ${revision}`;

async function membership(uid){const snap=await getDocs(query(collection(db,"householdMembers"),where("uid","==",uid)));if(snap.empty)return null;const d=snap.docs.find(x=>x.data().status==="active")||snap.docs[0];return{id:d.id,...d.data()}}
function localJson(){return JSON.stringify(window.hestia.getState())}
function isOwner(){return role==="owner"}

async function writeState(json,initialize=false){const next=revision+1;await setDoc(stateRef,{valueJson:json,revision:next,schemaVersion:15,updatedAt:serverTimestamp(),updatedBy:user.uid,...(initialize?{initializedAt:serverTimestamp(),initializedBy:user.uid}:{})},{merge:true});await waitForPendingWrites(db);revision=next;status("online","● Synced")}
async function flush(){if(!cloudReady||remote||saving||!pendingJson)return;saving=true;const json=pendingJson;pendingJson="";status("","● Syncing");try{await writeState(json)}catch(e){pendingJson=json;console.error("Cloud save failed",e);status("error","● Save failed");alert("Firestore save failed: "+e.message)}finally{saving=false}}

window.hestiaInitializeCloud=async()=>{if(!isOwner())return alert("Only the household owner can initialize cloud data.");if(!confirm("Use the data currently shown on this device as the shared household data?"))return;status("","● Initializing");try{await writeState(localJson(),true);hideCloudSetup();cloudReady=true;listenState()}catch(e){status("error","● Init failed");alert("Cloud initialization failed: "+e.message)}};
window.hestiaReplaceCloud=async()=>{if(!isOwner())return alert("Only the household owner can replace cloud data.");if(!confirm("Replace shared cloud data with the data currently shown on this device? This cannot be undone."))return;status("","● Syncing");try{await writeState(localJson(),true);hideCloudSetup()}catch(e){status("error","● Save failed");alert(e.message)}};
window.hestiaCloseCloud=()=>hideCloudSetup();
window.hestiaCloudTools=()=>showCloudSetup({title:"Cloud synchronization",message:isOwner()?"The owner can replace shared data from this device. Download a JSON backup first if the current device has the correct records.":"Cloud data is controlled by the household owner.",diagnostics:diagnostic(),actions:isOwner()?[{label:"Replace cloud from this device",handler:"hestiaReplaceCloud",primary:true},{label:"Close",handler:"hestiaCloseCloud"}]:[{label:"Close",handler:"hestiaCloseCloud"}]});
window.hestiaForceSync=async()=>{if(!cloudReady)return window.hestiaCloudTools();pendingJson=localJson();await flush()};

function listenState(){unsubState?.();unsubState=onSnapshot(stateRef,{includeMetadataChanges:true},snap=>{if(!snap.exists())return;const data=snap.data(),json=data.valueJson;if(!json)return;revision=Number(data.revision||0);try{remote=true;window.hestia.setState(JSON.parse(json));cloudReady=true;hideCloudSetup();status(snap.metadata.hasPendingWrites?"":"online",snap.metadata.hasPendingWrites?"● Syncing":`● Synced r${revision}`)}catch(e){console.error("Invalid cloud state",e);status("error","● Invalid cloud data")}finally{remote=false}},e=>{console.error("State listener failed",e);status("error","● Sync error")})}

async function load(m){member=m;householdId=m.householdId;role=m.role||"member";if(m.status==="pending"){login.classList.add("hide");familySetup.classList.remove("hide");createFamily.classList.add("hide");joinFamily.parentElement.classList.add("hide");setupMsg.textContent="Awaiting owner/admin approval.";return}login.classList.add("hide");familySetup.classList.add("hide");window.hestia.setUser({displayName:m.displayName||user.displayName||user.email,email:user.email,role});unsubMembers?.();unsubMembers=onSnapshot(query(collection(db,"householdMembers"),where("householdId","==",householdId)),snap=>{const members=snap.docs.map(d=>({id:d.id,...d.data()}));window.hestia.setMembers(members);const me=members.find(x=>x.uid===user.uid);if(me){role=me.role||role;window.hestia.setUser({displayName:me.displayName||user.displayName||user.email,email:user.email,role})}});
stateRef=doc(db,"households",householdId,"app","state");status("","● Checking cloud");const cloud=await getDoc(stateRef);if(!cloud.exists()||!cloud.data().valueJson){cloudReady=false;showCloudSetup({title:isOwner()?"Initialize shared household":"Waiting for household setup",message:isOwner()?"No shared cloud data exists. Confirm that this device contains the correct household information, then initialize it. New devices cannot initialize sample data.":"The household owner must initialize shared data from the owner device before this device can be used.",diagnostics:diagnostic(),actions:isOwner()?[{label:"Initialize from this device",handler:"hestiaInitializeCloud",primary:true}]:[]});status("error",isOwner()?"● Setup required":"● Waiting for owner");return}
revision=Number(cloud.data().revision||0);listenState();window.hestia.setCloudSave=value=>{if(remote||!cloudReady)return;pendingJson=JSON.stringify(value);clearTimeout(saveTimer);saveTimer=setTimeout(flush,300)}}

googleBtn.onclick=()=>signInWithPopup(auth,provider).catch(e=>loginMsg.textContent=e.message);logoutBtn.onclick=()=>signOut(auth);
createFamily.onclick=async()=>{const name=prompt("Household name:","My household")?.trim();if(!name)return;const h=doc(collection(db,"households"));createFamily.disabled=true;try{await runTransaction(db,async tx=>{tx.set(h,{name,ownerUid:user.uid,createdAt:serverTimestamp()});tx.set(doc(db,"householdMembers",`${h.id}_${user.uid}`),{householdId:h.id,uid:user.uid,email:user.email||"",displayName:user.displayName||user.email,role:"owner",status:"active",joinedAt:serverTimestamp()})});await load({householdId:h.id,uid:user.uid,displayName:user.displayName,role:"owner",status:"active"})}catch(e){setupMsg.textContent=e.message}finally{createFamily.disabled=false}};
joinFamily.onclick=async()=>{const code=inviteCode.value.trim().toUpperCase();try{await runTransaction(db,async tx=>{const ir=doc(db,"householdInvites",code),inv=await tx.get(ir);if(!inv.exists()||!inv.data().active)throw Error("Invalid invitation code");const h=inv.data().householdId;tx.set(doc(db,"householdMembers",`${h}_${user.uid}`),{householdId:h,uid:user.uid,email:user.email||"",displayName:user.displayName||user.email,role:"member",status:"pending",joinedAt:serverTimestamp()});tx.update(ir,{active:false,usedBy:user.uid,usedAt:serverTimestamp()})});await load(await membership(user.uid))}catch(e){setupMsg.textContent=e.message}};
inviteBtn.onclick=async()=>{if(!["owner","admin"].includes(role))return alert("Only an owner or admin can invite.");const code=Math.random().toString(36).slice(2,8).toUpperCase();await setDoc(doc(db,"householdInvites",code),{householdId,active:true,createdBy:user.uid,createdAt:serverTimestamp()});prompt("Share this invitation code:",code)};
window.hestiaAddManualMember=async(name,manualRole)=>{if(!["owner","admin"].includes(role))return alert("Only an owner or admin can add members.");await setDoc(doc(collection(db,"householdMembers")),{householdId,uid:"",email:"",displayName:name,role:manualRole,status:"active",manual:true,createdBy:user.uid,joinedAt:serverTimestamp()})};
window.hestiaApproveMember=async id=>{if(!["owner","admin"].includes(role))return;await setDoc(doc(db,"householdMembers",id),{status:"active",role:"member",approvedBy:user.uid,approvedAt:serverTimestamp()},{merge:true})};
window.hestiaRemoveMember=async id=>{if(!["owner","admin"].includes(role))return;const{deleteDoc}=await import("https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js");await deleteDoc(doc(db,"householdMembers",id))};
window.addEventListener("online",()=>{status("","● Reconnecting");enableNetwork(db).catch(console.error)});window.addEventListener("offline",()=>status("error","● Offline"));
onAuthStateChanged(auth,async u=>{user=u;if(!u){unsubState?.();unsubMembers?.();cloudReady=false;login.classList.remove("hide");familySetup.classList.add("hide");return}window.hestia.setUser({displayName:u.displayName||u.email,email:u.email,role:"member"});try{const m=await membership(u.uid);if(m)await load(m);else{login.classList.add("hide");familySetup.classList.remove("hide")}}catch(e){console.error(e);loginMsg.textContent=e.message}});
